const CONFIG = {
  spreadsheetId: '1To6WfnCyCn8ms7o1KQ5M_UOtvmk2yO1uH50g1rjA8Eg',
  spreadsheetUrl: 'https://docs.google.com/spreadsheets/d/1To6WfnCyCn8ms7o1KQ5M_UOtvmk2yO1uH50g1rjA8Eg/edit',
  pageSize: 20,
  credentials: { username: 'harga1900', password: 'harga1900' }
};
const state={raw:[],filtered:[],page:1,charts:{}};
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').trim();
const key=v=>norm(v).toLowerCase().replace(/[^a-z0-9]/g,'');
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:null;const s=norm(v).replace(/\s/g,'').replace(/\.(?=\d{3}(\D|$))/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null};
const fmtInt=v=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(v||0);
const fmtMoney=v=>v==null?'–':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
const fmtPct=v=>v==null?'–':`${v>=0?'+':''}${v.toFixed(2).replace('.',',')}%`;
function pick(row,aliases){for(const alias of aliases){const f=Object.entries(row).find(([k])=>key(k)===key(alias));if(f)return f[1]}return''}
function currentPeriod(){return $('periodFilter').value}
function periodMeta(){const p=currentPeriod();if(p==='bulanan')return{prev:['PREV'],current:['CURRENT'],prevLabel:'Harga bulan sebelumnya',currentLabel:'Harga bulan berjalan',prevHeader:'Prev',currentHeader:'Current'};return{prev:['AVR PREV'],current:['AVR CURRENT'],prevLabel:'Rata-rata bulanan sebelumnya',currentLabel:'Rata-rata bulanan saat ini',prevHeader:'AVR Prev',currentHeader:'AVR Current'}}
function normalizeRow(row){const meta=periodMeta();const prev=num(pick(row,meta.prev));const current=num(pick(row,meta.current));const rhRaw=num(pick(row,['RH']));const changePct=rhRaw!=null?rhRaw-100:(prev&&current!=null?((current/prev)-1)*100:null);return{kab:norm(pick(row,['Kab','KAB'])),commodity:norm(pick(row,['Komoditas'])),quality:norm(pick(row,['Kualitas'])),marketType:norm(pick(row,['Jenis Pasar'])),market:norm(pick(row,['Pasar'])),respondent:norm(pick(row,['Nama Responden'])),prev,current,changePct,flag:norm(pick(row,['FLAG'])),note:norm(pick(row,['KET']))}}
function sheetUrl(sheet){return`https://docs.google.com/spreadsheets/d/${CONFIG.spreadsheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}&range=A2:AZ`}
function updatePeriodLabels(){const m=periodMeta();$('avgPrevLabel').textContent=m.prevLabel;$('avgCurrentLabel').textContent=m.currentLabel;$('avgPrevSource').textContent=m.prevHeader;$('avgCurrentSource').textContent=m.currentHeader;$('prevTableHeader').textContent=m.prevHeader;$('currentTableHeader').textContent=m.currentHeader}
async function loadData(){const sheet=currentPeriod();updatePeriodLabels();setLoading(true);showStatus(`Memuat sheet ${sheet}…`,'info');try{const response=await fetch(sheetUrl(sheet),{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const csv=await response.text();const parsed=Papa.parse(csv,{header:true,skipEmptyLines:'greedy'});if(parsed.errors.length&&!parsed.data.length)throw new Error(parsed.errors[0].message);state.raw=parsed.data.map(normalizeRow).filter(r=>r.commodity||r.quality||r.respondent);state.page=1;populateFilters();applyFilters();$('lastUpdate').textContent=`Sheet ${sheet} • ${fmtInt(state.raw.length)} observasi • dimuat ${new Date().toLocaleString('id-ID')}`;hideStatus()}catch(err){state.raw=[];state.filtered=[];renderAll();showStatus('Data tidak dapat dimuat. Pastikan Google Sheets disetel “Siapa saja yang memiliki link dapat melihat”. Detail: '+err.message,'error');$('lastUpdate').textContent='Gagal terhubung ke Google Sheets'}finally{setLoading(false)}}
function setLoading(on){$('refreshBtn').disabled=on;$('refreshBtn').textContent=on?'Memuat…':'↻ Muat ulang'}function showStatus(t,type){const e=$('status');e.textContent=t;e.className=`status ${type}`}function hideStatus(){$('status').className='status hidden'}
function uniq(f){return[...new Set(state.raw.map(r=>r[f]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'id'))}function refill(id,v,l){const e=$(id),c=e.value;e.innerHTML=`<option value="">${l}</option>`+v.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(v.includes(c))e.value=c}function populateFilters(){refill('kabFilter',uniq('kab'),'Semua wilayah');refill('commodityFilter',uniq('commodity'),'Semua komoditas');refill('marketFilter',uniq('marketType'),'Semua jenis pasar')}
function applyFilters(){const kab=$('kabFilter').value,com=$('commodityFilter').value,mt=$('marketFilter').value,q=key($('searchFilter').value);state.filtered=state.raw.filter(r=>(!kab||r.kab===kab)&&(!com||r.commodity===com)&&(!mt||r.marketType===mt)&&(!q||key([r.quality,r.market,r.respondent,r.commodity].join(' ')).includes(q)));state.page=1;renderAll()}
function stats(){const valid=state.filtered.filter(r=>r.changePct!=null),up=valid.filter(r=>r.changePct>.005).length,down=valid.filter(r=>r.changePct<-.005).length,stable=valid.length-up-down,extreme=valid.filter(r=>Math.abs(r.changePct)>=20).length,missing=state.filtered.filter(r=>r.current==null||r.current===0).length;const prevVals=state.filtered.map(r=>r.prev).filter(v=>v!=null&&v>0),curVals=state.filtered.map(r=>r.current).filter(v=>v!=null&&v>0);const avgPrev=prevVals.length?prevVals.reduce((a,b)=>a+b,0)/prevVals.length:null,avgCurrent=curVals.length?curVals.reduce((a,b)=>a+b,0)/curVals.length:null,avgChange=avgPrev&&avgCurrent!=null?((avgCurrent/avgPrev)-1)*100:null;return{total:state.filtered.length,valid:valid.length,up,down,stable,extreme,missing,avgPrev,avgCurrent,avgChange}}
function share(n,d){return d?`${(n/d*100).toFixed(1).replace('.',',')}% dari data valid`:'Tidak ada data valid'}
function renderKpis(s){$('kpiTotal').textContent=fmtInt(s.total);$('kpiUp').textContent=fmtInt(s.up);$('kpiDown').textContent=fmtInt(s.down);$('kpiStable').textContent=fmtInt(s.stable);$('kpiExtreme').textContent=fmtInt(s.extreme);$('kpiUpShare').textContent=share(s.up,s.valid);$('kpiDownShare').textContent=share(s.down,s.valid);$('kpiStableShare').textContent=share(s.stable,s.valid);$('avgPrev').textContent=fmtMoney(s.avgPrev);$('avgCurrent').textContent=fmtMoney(s.avgCurrent);const ac=$('avgChange');ac.textContent=fmtPct(s.avgChange);ac.className=s.avgChange>0?'positive':s.avgChange<0?'negative':''}
function groupedAverage(field){const m={};state.filtered.forEach(r=>{if(r[field]&&r.changePct!=null)(m[r[field]]??=[]).push(r.changePct)});return Object.entries(m).map(([label,v])=>({label,value:v.reduce((a,b)=>a+b,0)/v.length}))}
function makeChart(id,type,data,options){if(state.charts[id])state.charts[id].destroy();state.charts[id]=new Chart($(id),{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:10,usePointStyle:true,font:{size:10}}}},scales:type==='doughnut'?{}:{x:{grid:{display:false}},y:{grid:{color:'#edf1f6'}}},...options}})}
function renderCharts(s){makeChart('compositionChart','doughnut',{labels:['Naik','Turun','Tetap'],datasets:[{data:[s.up,s.down,s.stable],backgroundColor:['#16855b','#d64545','#94a3b8'],borderWidth:0}]},{cutout:'66%'});const top=groupedAverage('commodity').sort((a,b)=>b.value-a.value).slice(0,10).reverse();makeChart('topCommodityChart','bar',{labels:top.map(x=>x.label),datasets:[{label:'Rata-rata perubahan (%)',data:top.map(x=>+x.value.toFixed(2)),backgroundColor:'#1f6feb',borderRadius:5}]},{indexAxis:'y',plugins:{legend:{display:false}}});const markets=groupedAverage('marketType').sort((a,b)=>b.value-a.value);makeChart('marketChart','bar',{labels:markets.map(x=>x.label),datasets:[{label:'Rata-rata perubahan (%)',data:markets.map(x=>+x.value.toFixed(2)),backgroundColor:'#0ea5a4',borderRadius:6}]},{plugins:{legend:{display:false}}});makeChart('qualityChart','doughnut',{labels:['Harga tersedia','Harga kosong/0'],datasets:[{data:[Math.max(0,s.total-s.missing),s.missing],backgroundColor:['#1f6feb','#f0a13a'],borderWidth:0}]},{cutout:'66%'})}
function renderEvaluation(s){const valid=state.filtered.filter(r=>r.changePct!=null),avg=valid.length?valid.reduce((a,b)=>a+b.changePct,0)/valid.length:0,topUp=[...valid].sort((a,b)=>b.changePct-a.changePct)[0],topDown=[...valid].sort((a,b)=>a.changePct-b.changePct)[0],extremeShare=s.valid?s.extreme/s.valid*100:0,level=extremeShare>=10?'high':extremeShare>=3?'medium':'low';const badge=$('riskBadge');badge.className=`badge ${level}`;badge.textContent={low:'Risiko rendah',medium:'Perlu perhatian',high:'Prioritas evaluasi'}[level];const trend=avg>.05?'cenderung meningkat':avg<-.05?'cenderung menurun':'relatif stabil';$('evaluationText').innerHTML=`<div class="eval-item"><strong>Rata-rata periode</strong><p>Rata-rata harga sebelumnya sebesar ${fmtMoney(s.avgPrev)} dan rata-rata harga saat ini sebesar ${fmtMoney(s.avgCurrent)}, atau berubah ${fmtPct(s.avgChange)}.</p></div><div class="eval-item"><strong>Gambaran umum</strong><p>Dari ${fmtInt(s.valid)} observasi valid, harga ${trend}. Sebanyak ${fmtInt(s.extreme)} observasi mengalami perubahan minimal 20%.</p></div><div class="eval-item"><strong>Tindak lanjut</strong><p>${topUp&&topUp.changePct>0?`Kenaikan terbesar terdapat pada ${escapeHtml(topUp.commodity)} (${fmtPct(topUp.changePct)}). `:''}${topDown&&topDown.changePct<0?`Penurunan terbesar terdapat pada ${escapeHtml(topDown.commodity)} (${fmtPct(topDown.changePct)}). `:''}${s.missing?`Lengkapi ${fmtInt(s.missing)} harga yang kosong atau nol.`:'Pertahankan pemeriksaan rutin antarperiode.'}</p></div>`}
function statusOf(r){if(r.changePct==null)return['Tidak valid','stable'];if(r.changePct>.005)return['Naik',`up${Math.abs(r.changePct)>=20?' extreme':''}`];if(r.changePct<-.005)return['Turun',`down${Math.abs(r.changePct)>=20?' extreme':''}`];return['Tetap','stable']}
function renderTable(){const sorted=[...state.filtered].sort((a,b)=>Math.abs(b.changePct??-1)-Math.abs(a.changePct??-1)),pages=Math.max(1,Math.ceil(sorted.length/CONFIG.pageSize));state.page=Math.min(state.page,pages);const rows=sorted.slice((state.page-1)*CONFIG.pageSize,state.page*CONFIG.pageSize);$('dataBody').innerHTML=rows.length?rows.map(r=>{const st=statusOf(r);return`<tr><td>${escapeHtml(r.kab||'–')}</td><td><strong>${escapeHtml(r.commodity||'–')}</strong></td><td>${escapeHtml(r.quality||'–')}</td><td>${escapeHtml(r.marketType||'–')}</td><td>${escapeHtml(r.respondent||'–')}</td><td class="num">${fmtMoney(r.prev)}</td><td class="num">${fmtMoney(r.current)}</td><td class="num"><strong>${fmtPct(r.changePct)}</strong></td><td><span class="pill ${st[1]}">${st[0]}</span></td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Tidak ada data sesuai filter.</td></tr>';$('pageInfo').textContent=`Halaman ${state.page} dari ${pages}`;$('prevPage').disabled=state.page<=1;$('nextPage').disabled=state.page>=pages}
function renderAll(){const s=stats();renderKpis(s);renderCharts(s);renderEvaluation(s);renderTable()}function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function csvCell(v){const s=String(v??'');return/[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadCsv(){const m=periodMeta(),head=['Wilayah','Komoditas','Kualitas','Jenis Pasar','Pasar','Responden',m.prevHeader,m.currentHeader,'Perubahan Persen'],rows=state.filtered.map(r=>[r.kab,r.commodity,r.quality,r.marketType,r.market,r.respondent,r.prev,r.current,r.changePct]),blob=new Blob(['\ufeff'+[head,...rows].map(x=>x.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rekap-${currentPeriod().toLowerCase().replace(/\s/g,'-')}.csv`;a.click();URL.revokeObjectURL(a.href)}
function showDashboard(){sessionStorage.setItem('rekapHargaLogin','ok');$('loginScreen').classList.add('hidden');$('dashboardApp').classList.remove('hidden');loadData()}function logout(){sessionStorage.removeItem('rekapHargaLogin');location.reload()}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('username').value===CONFIG.credentials.username&&$('password').value===CONFIG.credentials.password){$('loginError').classList.add('hidden');showDashboard()}else $('loginError').classList.remove('hidden')});$('logoutBtn').addEventListener('click',logout);$('sheetBtn').href=CONFIG.spreadsheetUrl;$('periodFilter').addEventListener('change',loadData);['kabFilter','commodityFilter','marketFilter'].forEach(id=>$(id).addEventListener('change',applyFilters));$('searchFilter').addEventListener('input',applyFilters);$('refreshBtn').addEventListener('click',loadData);$('downloadBtn').addEventListener('click',downloadCsv);$('prevPage').addEventListener('click',()=>{state.page--;renderTable()});$('nextPage').addEventListener('click',()=>{state.page++;renderTable()});if(sessionStorage.getItem('rekapHargaLogin')==='ok')showDashboard();
