const CONFIG={
  spreadsheetId:'1To6WfnCyCn8ms7o1KQ5M_UOtvmk2yO1uH50g1rjA8Eg',
  appsScriptUrl:'PASTE_URL_WEB_APP_APPS_SCRIPT_DI_SINI',
  credentials:{username:'harga1900',password:'harga1900'},
  pageSize:25
};
const SHEETS={
  'Mingguan':{lastColumn:'Z',prevIndex:21,currentIndex:22,noteIndex:24,respondentIndex:10,noteColumn:'Y'},
  'Dwi Mingguan':{lastColumn:'Y',prevIndex:15,currentIndex:16,noteIndex:18,respondentIndex:10,noteColumn:'S'},
  'bulanan':{lastColumn:'U',prevIndex:11,currentIndex:12,noteIndex:14,respondentIndex:10,noteColumn:'O'}
};
const state={all:[],filtered:[],view:'dashboard',page:1,periodPage:1,sortKey:'change',sortDir:'desc',charts:{}};
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').trim();
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const priceNum=v=>{if(typeof v==='number')return Number.isFinite(v)?v:null;let s=norm(v).replace(/\s/g,'');if(!s)return null;if(s.includes(',')&&s.includes('.')){const decimal=s.lastIndexOf(',')>s.lastIndexOf('.')?',':'.',thousand=decimal===','?'.':',';s=s.split(thousand).join('').replace(decimal,'.')}else if(/^[-+]?\d{1,3}([.,]\d{3})+$/.test(s))s=s.replace(/[.,]/g,'');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null};
const fmtMoney=v=>v==null?'–':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
const fmtPct=v=>v==null?'–':`${v>=0?'+':''}${v.toFixed(2).replace('.',',')}%`;
const fmtInt=v=>new Intl.NumberFormat('id-ID').format(v||0);
const avg=arr=>{const a=arr.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};
const unique=(arr,key)=>[...new Set(arr.map(x=>x[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'id'));
function showStatus(msg,type='info'){const el=$('status');el.textContent=msg;el.className=`alert ${type}`;setTimeout(()=>el.classList.add('hidden'),5000)}
function currentPeriod(){return $('periodFilter').value}
function periodLabel(v){return v==='bulanan'?'Bulanan':v}
function csvUrl(sheet,cfg){return `https://docs.google.com/spreadsheets/d/${CONFIG.spreadsheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}&range=A2:${cfg.lastColumn}`}
async function fetchSheet(sheet,cfg){const res=await fetch(csvUrl(sheet,cfg),{cache:'no-store'});if(!res.ok)throw new Error(`Gagal membaca sheet ${sheet}`);const text=await res.text();const parsed=Papa.parse(text,{skipEmptyLines:true}).data;if(parsed.length<2)return[];return parsed.slice(1).map((r,i)=>{
  const prev=priceNum(r[cfg.prevIndex]),current=priceNum(r[cfg.currentIndex]);
  const change=prev&&current!=null?((current-prev)/prev)*100:null;
  return{sheet,period:periodLabel(sheet),rowNumber:i+3,kab:norm(r[0]),commodity:norm(r[2]),quality:norm(r[5]),marketType:norm(r[7]),market:norm(r[9]),respondent:norm(r[cfg.respondentIndex]),prev,current,change,note:norm(r[cfg.noteIndex]),noteColumn:cfg.noteColumn};
  }).filter(x=>x.commodity||x.respondent||x.prev!=null||x.current!=null);
}
async function loadAll(){showStatus('Memuat data dari tiga sheet...');try{const entries=Object.entries(SHEETS);const groups=await Promise.all(entries.map(([s,c])=>fetchSheet(s,c)));state.all=groups.flat();state.page=1;state.periodPage=1;populateFilters();applyFilters();$('lastUpdate').textContent=`Diperbarui ${new Date().toLocaleString('id-ID')}`;showStatus(`${fmtInt(state.all.length)} observasi berhasil dimuat.`)}catch(e){showStatus(`${e.message}. Pastikan spreadsheet dapat diakses oleh siapa saja yang memiliki link.`,'error')}}
function populateSelect(id,items,placeholder){const el=$(id),old=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(items.includes(old))el.value=old}
function populateFilters(){populateSelect('kabFilter',unique(state.all,'kab'),'Semua wilayah');populateSelect('commodityFilter',unique(state.all,'commodity'),'Semua komoditas');populateSelect('marketTypeFilter',unique(state.all,'marketType'),'Semua jenis pasar');populateSelect('commodityFocus',unique(state.all,'commodity'),'Pilih komoditas')}
function applyFilters(){const p=currentPeriod(),kab=$('kabFilter').value,kom=$('commodityFilter').value,mt=$('marketTypeFilter').value,q=norm($('searchFilter').value).toLowerCase(),extreme=$('extremeOnly').checked;state.filtered=state.all.filter(x=>(p==='Semua'||x.sheet===p)&&(!kab||x.kab===kab)&&(!kom||x.commodity===kom)&&(!mt||x.marketType===mt)&&(!q||[x.kab,x.commodity,x.quality,x.market,x.respondent,x.note,x.period].join(' ').toLowerCase().includes(q))&&(!extreme||(Number.isFinite(x.change)&&Math.abs(x.change)>=20)));state.page=1;state.periodPage=1;renderAll()}
function statusOf(c){if(!Number.isFinite(c)||Math.abs(c)<0.005)return 'Tetap';return c>0?'Naik':'Turun'}
function sortedData(){const arr=[...state.filtered],k=state.sortKey,d=state.sortDir==='asc'?1:-1;return arr.sort((a,b)=>{let av=a[k],bv=b[k];if(typeof av==='number'||typeof bv==='number'){av=Number.isFinite(av)?av:-Infinity;bv=Number.isFinite(bv)?bv:-Infinity;return(av-bv)*d}return String(av??'').localeCompare(String(bv??''),'id')*d})}
function renderAll(){renderHeader();renderDashboard();renderPeriod();renderCommodity();renderMarket();renderEvaluation();renderRecap();updateSortMarks()}
function renderHeader(){$('heroPeriod').textContent=currentPeriod()==='Semua'?'Semua Periode':periodLabel(currentPeriod());$('periodBadge').textContent=$('heroPeriod').textContent}
function destroyChart(id){if(state.charts[id])state.charts[id].destroy()}
function chart(id,type,labels,data,label){destroyChart(id);state.charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label,data}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut'}},scales:type==='doughnut'?{}:{y:{beginAtZero:true}}}})}
function groupAvg(data,key,value='change'){const m={};data.forEach(x=>{if(!x[key]||!Number.isFinite(x[value]))return;(m[x[key]]??=[]).push(x[value])});return Object.entries(m).map(([name,v])=>({name,value:avg(v)}))}
function renderDashboard(){const d=state.filtered,up=d.filter(x=>x.change>0),down=d.filter(x=>x.change<0),stable=d.filter(x=>Number.isFinite(x.change)&&Math.abs(x.change)<.005),ext=d.filter(x=>Number.isFinite(x.change)&&Math.abs(x.change)>=20);$('kpiTotal').textContent=fmtInt(d.length);$('kpiUp').textContent=fmtInt(up.length);$('kpiDown').textContent=fmtInt(down.length);$('kpiStable').textContent=fmtInt(stable.length);$('kpiExtreme').textContent=fmtInt(ext.length);$('conditionScore').textContent=fmtInt(ext.length);const ap=avg(d.map(x=>x.prev)),ac=avg(d.map(x=>x.current));$('avgPrev').textContent=fmtMoney(ap);$('avgCurrent').textContent=fmtMoney(ac);$('avgChange').textContent=ap?fmtPct(((ac-ap)/ap)*100):'–';$('heroNarrative').textContent=`Menampilkan ${fmtInt(d.length)} observasi sesuai filter aktif; ${fmtInt(ext.length)} di antaranya berubah minimal 20 persen.`;chart('compositionChart','doughnut',['Naik','Turun','Tetap'],[up.length,down.length,stable.length],'Observasi');const top=groupAvg(d,'commodity').sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,10);chart('topIncreaseChart','bar',top.map(x=>x.name),top.map(x=>x.value),'Perubahan (%)')}
function noteCell(x){return `<textarea class="editable-note" id="note-${x.sheet.replace(/\s/g,'_')}-${x.rowNumber}">${esc(x.note)}</textarea>`}
function saveButton(x){return `<button class="btn primary save-note" data-sheet="${esc(x.sheet)}" data-row="${x.rowNumber}" data-note-id="note-${x.sheet.replace(/\s/g,'_')}-${x.rowNumber}">Simpan</button>`}
function rowHtml(x,recap=false){return `<tr class="${Math.abs(x.change||0)>=20?'extreme-row':''}"><td>${esc(x.period)}</td><td>${esc(x.kab)}</td><td>${esc(x.commodity)}</td><td>${esc(x.quality)}</td>${recap?`<td>${esc(x.marketType)}</td>`:''}<td>${esc(x.market)}</td><td>${esc(x.respondent)}</td><td class="num">${fmtMoney(x.prev)}</td><td class="num">${fmtMoney(x.current)}</td><td class="num"><span class="pill ${x.change>0?'up':x.change<0?'down':'stable'} extreme">${fmtPct(x.change)}</span></td><td>${noteCell(x)}</td><td>${saveButton(x)}</td></tr>`}
function paginate(data,page){const pages=Math.max(1,Math.ceil(data.length/CONFIG.pageSize));page=Math.min(page,pages);return{rows:data.slice((page-1)*CONFIG.pageSize,page*CONFIG.pageSize),pages,page}}
function renderPeriod(){const d=sortedData();$('periodCommodities').textContent=fmtInt(unique(d,'commodity').length);$('periodMarkets').textContent=fmtInt(unique(d,'market').length);$('periodRespondents').textContent=fmtInt(unique(d,'respondent').length);$('periodExtreme').textContent=fmtInt(d.filter(x=>Math.abs(x.change||0)>=20).length);const p=paginate(d,state.periodPage);state.periodPage=p.page;$('periodTableBody').innerHTML=p.rows.map(x=>rowHtml(x,false)).join('')||'<tr><td colspan="11">Tidak ada data sesuai filter.</td></tr>';$('periodPageInfo').textContent=`Halaman ${p.page} dari ${p.pages} • ${fmtInt(d.length)} data`;bindSaveButtons()}
function renderRecap(){const d=sortedData(),p=paginate(d,state.page);state.page=p.page;$('recapBody').innerHTML=p.rows.map(x=>rowHtml(x,true)).join('')||'<tr><td colspan="12">Tidak ada data sesuai filter.</td></tr>';$('pageInfo').textContent=`Halaman ${p.page} dari ${p.pages} • ${fmtInt(d.length)} data`;bindSaveButtons()}
async function saveNote(btn){const url=CONFIG.appsScriptUrl;if(!url||url.includes('PASTE_URL')){showStatus('URL Web App Apps Script belum diisi pada CONFIG.appsScriptUrl di script.js. Ikuti README.','error');return}const sheet=btn.dataset.sheet,row=Number(btn.dataset.row),note=$(btn.dataset.noteId).value;btn.classList.add('saving');btn.textContent='Menyimpan...';try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'updateNote',sheet,row,note,token:'harga1900'})});const out=await res.json();if(!out.ok)throw new Error(out.message||'Gagal menyimpan');const item=state.all.find(x=>x.sheet===sheet&&x.rowNumber===row);if(item)item.note=note;showStatus(`Keterangan ${sheet} baris ${row} berhasil disimpan.`)}catch(e){showStatus(`Gagal menyimpan: ${e.message}`,'error')}finally{btn.classList.remove('saving');btn.textContent='Simpan'}}
function bindSaveButtons(){document.querySelectorAll('.save-note').forEach(b=>{b.onclick=()=>saveNote(b)})}
function renderCommodity(){const focus=$('commodityFocus').value||state.filtered[0]?.commodity||'';if(focus&&!$('commodityFocus').value)$('commodityFocus').value=focus;const d=state.filtered.filter(x=>x.commodity===focus),ap=avg(d.map(x=>x.prev)),ac=avg(d.map(x=>x.current));$('commodityPrev').textContent=fmtMoney(ap);$('commodityCurrent').textContent=fmtMoney(ac);$('commodityChange').textContent=ap?fmtPct(((ac-ap)/ap)*100):'–';$('commodityObs').textContent=fmtInt(d.length);const g=groupAvg(d,'kab').sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,15);chart('commodityRegionChart','bar',g.map(x=>x.name),g.map(x=>x.value),'Perubahan (%)')}
function renderMarket(){const g=groupAvg(state.filtered,'market').sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,15);chart('marketRankingChart','bar',g.map(x=>x.name),g.map(x=>x.value),'Perubahan (%)')}
function renderEvaluation(){const d=state.filtered,ext=d.filter(x=>Math.abs(x.change||0)>=20),missing=d.filter(x=>x.prev==null||x.current==null),up=ext.filter(x=>x.change>0),down=ext.filter(x=>x.change<0);$('riskBadge').textContent=ext.length>50?'Perlu perhatian tinggi':ext.length?'Perlu verifikasi':'Relatif stabil';$('evaluationCards').innerHTML=`<article class="evaluation-card"><strong>Kenaikan ekstrem</strong><div class="metric">${fmtInt(up.length)}</div><p>Observasi naik minimal 20%.</p></article><article class="evaluation-card"><strong>Penurunan ekstrem</strong><div class="metric">${fmtInt(down.length)}</div><p>Observasi turun minimal 20%.</p></article><article class="evaluation-card"><strong>Data kosong</strong><div class="metric">${fmtInt(missing.length)}</div><p>Prev atau current belum terisi.</p></article>`;const priorities=[...ext].sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,20);$('priorityList').innerHTML=priorities.map(x=>`<div class="priority-item"><div class="priority-icon">!</div><div><strong>${esc(x.commodity)} — ${esc(x.respondent)}</strong><p>${esc(x.period)} • ${esc(x.market)} • ${esc(x.kab)}</p></div><div class="priority-value">${fmtPct(x.change)}</div></div>`).join('')||'<p class="muted">Tidak ada perubahan ekstrem sesuai filter.</p>'}
function updateSortMarks(){document.querySelectorAll('th[data-sort]').forEach(th=>{th.querySelector('.sort-mark')?.remove();if(th.dataset.sort===state.sortKey)th.insertAdjacentHTML('beforeend',`<span class="sort-mark">${state.sortDir==='asc'?'▲':'▼'}</span>`)})}
function bindSort(){document.querySelectorAll('th[data-sort]').forEach(th=>th.addEventListener('click',()=>{const k=th.dataset.sort;if(state.sortKey===k)state.sortDir=state.sortDir==='asc'?'desc':'asc';else{state.sortKey=k;state.sortDir=k==='change'?'desc':'asc'}renderPeriod();renderRecap();updateSortMarks()}))}
function downloadCsv(){const rows=sortedData(),headers=['Periode','Wilayah','Komoditas','Kualitas','Jenis Pasar','Pasar','Nama Responden','Prev','Current','Perubahan (%)','Keterangan'];const csv=Papa.unparse([headers,...rows.map(x=>[x.period,x.kab,x.commodity,x.quality,x.marketType,x.market,x.respondent,x.prev,x.current,x.change,x.note])]);const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rekap-monitoring-harga.csv';a.click();URL.revokeObjectURL(a.href)}
function switchView(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`view-${view}`).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const titles={dashboard:['Dashboard','Ringkasan perkembangan harga.'],period:['Analisis Periode','Mingguan, Dwi Mingguan, Bulanan, atau seluruh periode.'],commodity:['Analisis Komoditas','Perbandingan komoditas terpilih.'],market:['Analisis Pasar','Peringkat pasar berdasarkan perubahan.'],evaluation:['Evaluasi','Prioritas verifikasi perubahan harga.'],recap:['Rekap Data','Tabel data yang dapat diurutkan dan diedit.']};$('pageTitle').textContent=titles[view][0];$('pageSubtitle').textContent=titles[view][1];$('sidebar').classList.remove('open')}
function init(){const logged=sessionStorage.getItem('hargaLogin')==='1';$('loginScreen').classList.toggle('hidden',logged);$('app').classList.toggle('hidden',!logged);$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('username').value===CONFIG.credentials.username&&$('password').value===CONFIG.credentials.password){sessionStorage.setItem('hargaLogin','1');$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');loadAll()}else{$('loginError').textContent='Username atau password salah.';$('loginError').classList.remove('hidden')}});$('logoutBtn').onclick=()=>{sessionStorage.removeItem('hargaLogin');location.reload()};$('refreshBtn').onclick=loadAll;$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));['periodFilter','kabFilter','commodityFilter','marketTypeFilter','extremeOnly'].forEach(id=>$(id).addEventListener('change',applyFilters));$('searchFilter').addEventListener('input',applyFilters);$('commodityFocus').addEventListener('change',renderCommodity);$('prevPage').onclick=()=>{if(state.page>1){state.page--;renderRecap()}};$('nextPage').onclick=()=>{state.page++;renderRecap()};$('periodPrevPage').onclick=()=>{if(state.periodPage>1){state.periodPage--;renderPeriod()}};$('periodNextPage').onclick=()=>{state.periodPage++;renderPeriod()};$('downloadBtn').onclick=downloadCsv;bindSort();if(logged)loadAll()}
document.addEventListener('DOMContentLoaded',init);
